# Welcome to Jekyll!

title: BostonHacks
email: contact@bostonhacks.io
description: >- # this means to ignore newlines until "baseurl:"
  BostonHacks - Boston's premier collegiate MLH hackathon.
  Join over 450 students in a weekend of hacking, learning, and fun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: boston_hacks
github_username:  bostonhacks

# Build settings
markdown: kramdown


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
